# configs/model/CLIP-ViT-B.yaml
# @package _group_
backbone: "openai/clip-vit-base-patch32"
# any other CLIP-B-specific params, e.g.:
embed_dim: 512
alpha: 50

# equivalent to temperature
s: 100

# toggle to utilize alternate form of matrix multiplication 
HvProjection: True