# configs/defaults.yaml

version_base: 1

# === Hydra config groups to compose ===
defaults:
  - scheduler: CosineAnnealingWarmRestarts
  - model: CLIP-ViT-B
  - _self_

# === DDP setup from environment ===
# local_rank: ${oc.env:LOCAL_RANK}
# world_size: ${oc.env:WORLD_SIZE}
master:
  addr:     ${env:MASTER_ADDR, localhost}
  port:     ${env:MASTER_PORT, 12356}

# === Experiment metadata ===
exp_group:  data-augments-tests
exp_name:   new-da-2
exp_desc:   

optim:
  base_lr:      1.6473849365087354e-05
  weight_decay: 0.00015529

# === joint embedding switch ===
joint_embed: true

# === Training loop settings ===
# Number of total epochs to run
epochs:     10

# Save a checkpoint every N epochs (and on best)
save_every: 5

train:
  print_freq: 10  # log every 10 iters (adjust as you like)

  # how often to write a checkpoint (in epochs)


# === Data settings ===
data:
  dataset:      HAR
  batch_size:   96
  num_workers:  0
  validation:   false
  test_size:    0.2
  seed:         42
  shuffle:      true
  transform:
    size:          224
    scale:         [0.9, 1.0]
    interpolation: BICUBIC
    to_rgb:        true
    normalize:
      mean: [0.48145466, 0.4578275, 0.40821073]
      std:  [0.26862954, 0.26130258, 0.27577711]

# === Model choice (will load configs/model/CLIP-ViT-B.yaml) ===
num_classes:  15

# === Loss & Optimizer ===
loss:
  name: Sign

# === EMA switch ===
use_ema: true