# configs/defaults.yaml

version_base: 1

# === Training loop settings ===
epochs:     5
save_every: 2
train:
  print_freq: 10  # log every 10 iters

# === DDP setup from environment ===
# local_rank: ${oc.env:LOCAL_RANK}
# world_size: ${oc.env:WORLD_SIZE}
master:
  addr:     ${env:MASTER_ADDR, localhost}
  port:     ${env:MASTER_PORT, 12356}

# === Experiment metadata ===
project: HAR-ver2
exp_group: finalRuns
exp_name:   linear-classifier-HVprojection-6-prompt
exp_desc:   
save_code: True


# === Building model ===
defaults:
  - scheduler: CosineAnnealingWarmRestarts
  - model: CLIP-ViT-B
  - _self_
joint_embed: True
num_classes:  15

# === Loss & Optimizer ===
loss:
  name: Sign
optim:
  base_lr:      1.5e-05
  weight_decay: 1.0e-04
use_ema: True

# === Data settings ===
data:
  dataset:      HAR
  batch_size:   96
  num_workers:  0
  validation:   False
  test_size:    0.2
  seed:         42
  shuffle:      True
  transform:
    size:          224
    scale:         [0.9, 1.0]
    interpolation: BICUBIC
    to_rgb:        True
    normalize:
      mean: [0.48145466, 0.4578275, 0.40821073]
      std:  [0.26862954, 0.26130258, 0.27577711]