# configs/sweep.yaml
project: HAR-ver2
entity: rjl2194-columbia-university
program: train.py

method: bayes
metric:
  name: val/mAP
  goal: maximize

parameters:
  "optim.base_lr":
    distribution: log_uniform_values
    min: !!float 1e-7
    max: !!float 1e-2
  "optim.weight_decay":
    distribution: log_uniform_values
    min: !!float 1e-6
    max: !!float 1e-1

command:
  - ${env}                      # keep your environment (CUDA_VISIBLE_DEVICES, etc.)
  - python
  - -m
  - torch.distributed.run       # launch DDP
  - --standalone
  - --nnodes=1
  - --nproc_per_node=3
  - ${program}                  # train.py
  - ${args_no_hyphens}          # e.g. optim.base_lr=0.001
